MACOSX: If configured in release mode submit app for notarization

diff --git a/targets/macosx/package b/targets/macosx/package
--- a/targets/macosx/package
+++ b/targets/macosx/package
@@ -42,6 +42,24 @@ cd $SYS_PREFIX
 veval "zip -y -r $pkgfile $SYS_APPNAME$SYS_APPFIX"
 cd $here
 assertfile $pkgfile
+
+if [ $SYS_MODE = release ]; then
+  echo " => submitting zip archive for notarization.."
+  requestUUID=`xcrun altool --notarize-app --primary-bundle-id $SYS_PACKAGE_DOT -u $SYS_ORGEMAIL --password "@keychain:Developer-altool" -f $pkgfile | awk '/RequestUUID/ { print $NF; }'`
+  if [ "X$requestUUID" == "" ]; then
+    echo "ERROR: Upload to Apple for notarization failed!"
+    exit 1
+  else
+    echo " => checking notarization status [RequestUUID: $requestUUID].."
+    request_status="in progress"
+    while [ "$request_status" == "in progress" ]; do
+      echo "    waiting for progress.. "
+      sleep 10
+      request_status=`xcrun altool --notarization-info $requestUUID --username $SYS_ORGEMAIL --password "@keychain:Developer-altool" 2>&1 | awk -F ': ' '/Status:/ { print $2; }'`
+    done
+    xcrun altool --notarization-info $requestUUID --username $SYS_ORGEMAIL --password "@keychain:Developer-altool"
+  fi
+fi
 echo "=== $pkgfile"
 
 #eof
