LIBRARIES:  Check downloaded file sha-1 hash before use
This closes #40, but requires every user to have shasum available. A future version
may want to use sha256 instead of sha1, however sha256 is not available by default
on all platforms. While not all download sites offer https connections, if one is
available it will used. Unfortunately, this commit causes a rebuild of all libraries
used as their build.sh.in files are modified.

diff --git a/libraries/libcrypto/build.sh.in b/libraries/libcrypto/build.sh.in
--- a/libraries/libcrypto/build.sh.in
+++ b/libraries/libcrypto/build.sh.in
@@ -1,16 +1,21 @@
 #!/bin/sh
-
-PKGSRC=openssl-1.0.1h.tar.gz
+PKGHASH=74eed314fa2c93006df8d26cd9fc630a101abd76
+PKGSRC=openssl-1.0.1i.tar.gz
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
 
 if [ ! -f $src -a `which wget` ]; then
   echo "==> No source found, attempting to download.."
-  wget http://www.openssl.org/source/$PKGSRC -O $src
+  wget https://www.openssl.org/source/$PKGSRC -O $src
 fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libffts/build.sh.in b/libraries/libffts/build.sh.in
--- a/libraries/libffts/build.sh.in
+++ b/libraries/libffts/build.sh.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+PKGHASH=8318dc460413d952d2468c8bc9aa2e484bb72d98
 PKGSRC=ffts-0.7.tar.gz
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
@@ -10,6 +11,11 @@ fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libfreetype/build.sh.in b/libraries/libfreetype/build.sh.in
--- a/libraries/libfreetype/build.sh.in
+++ b/libraries/libfreetype/build.sh.in
@@ -1,5 +1,5 @@
 #!/bin/sh
-
+PKGHASH=d4a17b42505b23dab022f877e1849940aa3b64f3
 PKGURL=http://download.savannah.gnu.org/releases/freetype/freetype-2.5.3.tar.gz
 
 PKGSRC=`basename $PKGURL`
@@ -13,6 +13,11 @@ fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libgambc/build.sh.in b/libraries/libgambc/build.sh.in
--- a/libraries/libgambc/build.sh.in
+++ b/libraries/libgambc/build.sh.in
@@ -1,19 +1,21 @@
 #!/bin/sh
-
-# version of gambit to use:
-#GAMBIT=gambc-v4_6_9.tgz
-#GAMBIT=gambc-v4_6_7.tgz
+PKGHASH=2091784f1e332e8b5918718417abe75c2c9ada45
 GAMBIT=gambc-v4_7_0.tgz
 
 src=@SYS_PREFIXROOT@/packages/$GAMBIT
 
 if [ ! -f $src -a `which wget` ]; then
   echo "==> No source found, attempting to download.."
-  wget http://www.iro.umontreal.ca/~gambit/download/gambit/v4.7/source/$GAMBIT -O $src
+  wget https://www.iro.umontreal.ca/~gambit/download/gambit/v4.7/source/$GAMBIT -O $src
 fi
 
 if [ ! -f $src ]; then
   echo "ERROR: no source code found"
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libhpdf/build.sh.in b/libraries/libhpdf/build.sh.in
--- a/libraries/libhpdf/build.sh.in
+++ b/libraries/libhpdf/build.sh.in
@@ -1,5 +1,5 @@
 #!/bin/sh
-
+PKGHASH=b75ec6052b8d72aa7f23d67adcdf9df4847b64ca
 PKGSRC=libharu-2.2.1.tar.gz
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
@@ -11,6 +11,11 @@ fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libmosquitto/build.sh.in b/libraries/libmosquitto/build.sh.in
--- a/libraries/libmosquitto/build.sh.in
+++ b/libraries/libmosquitto/build.sh.in
@@ -1,14 +1,12 @@
 #!/bin/sh
-
-VERSION=1.3.1
+PKGHASH=b818672cc0db723995d7c3201ef6962931dd891a
+VERSION=1.3.4
 
 PKGURL="http://mosquitto.org/files/source/mosquitto-${VERSION}.tar.gz"
 PKGSRC=`basename $PKGURL`
-
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
 
 TIMESTAMP=`date "+%F %T%z"`
-
 options="-DWITH_TLS -DWITH_TLS_PSK"
 
 if [ ! -f $src -a `which wget` ]; then
@@ -18,6 +16,11 @@ fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libopus/build.sh.in b/libraries/libopus/build.sh.in
--- a/libraries/libopus/build.sh.in
+++ b/libraries/libopus/build.sh.in
@@ -1,5 +1,5 @@
 #!/bin/sh
-
+PKGHASH=35005f5549e2583f5770590135984dcfce6f3d58
 PKGSRC=opus-1.1.tar.gz
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
@@ -11,6 +11,11 @@ fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libpng/build.sh.in b/libraries/libpng/build.sh.in
--- a/libraries/libpng/build.sh.in
+++ b/libraries/libpng/build.sh.in
@@ -1,16 +1,21 @@
 #!/bin/sh
-
-PKGSRC=libpng-1.6.9.tar.gz
+PKGHASH=6bcd6efa7f20ccee51e70453426d7f4aea7cf4bb
+PKGSRC=libpng-1.6.12.tar.gz
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
 
 if [ ! -f $src -a `which wget` ]; then
   echo "==> No source found, attempting to download.."
-  wget http://prdownloads.sourceforge.net/libpng/$PKGSRC -O $src
+  wget https://prdownloads.sourceforge.net/libpng/$PKGSRC -O $src
 fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libportaudio/build.sh.in b/libraries/libportaudio/build.sh.in
--- a/libraries/libportaudio/build.sh.in
+++ b/libraries/libportaudio/build.sh.in
@@ -17,6 +17,7 @@ if [ @SYS_PLATFORM@ = openbsd ]; then
   done
 fi
 
+PKGHASH=526a7955de59016a06680ac24209ecb6ce05527d
 PKGSRC=pa_stable_v19_20140130.tgz
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
@@ -28,6 +29,11 @@ fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libsqlite/build.sh.in b/libraries/libsqlite/build.sh.in
--- a/libraries/libsqlite/build.sh.in
+++ b/libraries/libsqlite/build.sh.in
@@ -1,8 +1,8 @@
 #!/bin/sh
+PKGHASH=6f6ab5ee38eed46ee0d9a8cd8f1e13f94bba99b3
+VERSION=3080600
 
-VERSION=3080301
-
-PKGURL="http://www.sqlite.org/2014/sqlite-amalgamation-${VERSION}.zip"
+PKGURL="https://www.sqlite.org/2014/sqlite-amalgamation-${VERSION}.zip"
 PKGSRC=`basename $PKGURL`
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
@@ -14,6 +14,11 @@ fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libuuid/build.sh.in b/libraries/libuuid/build.sh.in
--- a/libraries/libuuid/build.sh.in
+++ b/libraries/libuuid/build.sh.in
@@ -1,16 +1,21 @@
 #!/bin/sh
-
-PKGSRC=libuuid-1.0.2.tar.gz
+PKGHASH=46eaedb875ae6e63677b51ec583656199241d597
+PKGSRC=libuuid-1.0.3.tar.gz
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
 
 if [ ! -f $src -a `which wget` ]; then
   echo "==> No source found, attempting to download.."
-  wget http://downloads.sourceforge.net/project/libuuid/$PKGSRC -O $src
+  wget https://downloads.sourceforge.net/project/libuuid/$PKGSRC -O $src
 fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
diff --git a/libraries/libz/build.sh.in b/libraries/libz/build.sh.in
--- a/libraries/libz/build.sh.in
+++ b/libraries/libz/build.sh.in
@@ -1,5 +1,5 @@
 #!/bin/sh
-
+PKGHASH=a4d316c404ff54ca545ea71a27af7dbc29817088
 PKGSRC=zlib-1.2.8.tar.gz
 
 src=@SYS_PREFIXROOT@/packages/$PKGSRC
@@ -11,6 +11,11 @@ fi
 
 if [ ! -f $src ]; then
   echo "==> ERROR: Unable to proceed. Please obtain $src first."
+  exit 1
+fi
+
+if [ `shasum $src | cut -f 1 -d " "` != "$PKGHASH" ]; then
+  echo "==> ERROR: Unable to proceed! SHA hash of download failed."
   exit 1
 fi
 
